engines:
  duplication:
    enabled: true
    exclude_paths:
      - crime_data/common/models.py
      - crime_data/common/cdemodels.py
      - crime_data/common/marshmallow_schemas.py
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"
exclude_paths:
  - tests/
  - crime_data/static/
  - migrations/
  - dba/
