engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"
exclude_paths:
  - tests/
  - crime_data/static/
  - migrations/
  - dba/
