applications:
- name: task-runner-update
  memory: 512M
  buildpack: python_buildpack
env:
  FLASK_APP: autoapp.py
  NEW_RELIC_CONFIG_FILE: newrelic.ini
  NEW_RELIC_LOG: stdout
command: cd dba/update && chmod u+x * && bash ./update_data.sh 2016 $PWD && curl https://s3.amazonaws.com/18f-cf-cli/psql-9.4.4-ubuntu-14.04.tar.gz | tar xvz && ./psql/bin/psql $DATABASE_URL -f update_reta.sql && ./psql/bin/psql $DATABASE_URL -f update_asr.sql  && echo SUCCESS || echo FAIL && sleep infinity
services:
- crime-data-upload-db
- crime-data-api-creds